-- Add keywords JSONB column to products and posts tables
ALTER TABLE products ADD COLUMN IF NOT EXISTS keywords JSONB DEFAULT '[]'::jsonb;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS product_keywords JSONB DEFAULT '[]'::jsonb;

COMMENT ON COLUMN products.keywords IS 'List of keywords for matching with content (e.g. ["cat", "toy"])';
COMMENT ON COLUMN posts.product_keywords IS 'List of keywords generated by AI to suggest products';
